### ISSUE TITLE
Issue with file deletion policy

### ISSUE THREAD

**Issue by cachapa** [jewel/clearskies#12]
https://github.com/jewel/clearskies/blob/master/protocol/core.md#deleted-files explains the file deletion policy which is used to avoid ghost copies.
However, that policy has a flaw where a file which has been deleted cannot be re-added to that share.

Testing with the latest client reveals this problem (machines A and B):
1. Add file test.txt to A
2. See file being correctly copied to B
3. Delete file on A
4. File is deleted on B
5. Re-add the file on A
6. File is not copied to B

Furthermore:
7. Copy the file manually to B
8. File is automatically deleted from A and B

In my view, this problem is as severe, if not worse than ghost copies, as it results in silent loss of data.

My proposal here would be to store the date of the file which was deleted along with the file name, and use it to decide whether any given file is a ghost or a new version.

**Comment by jewel** [comment]
Thanks for the excellent bug report!  A file with a newer "utime" should win over an entry with an older "utime", as explained in [the tree merge section](https://github.com/jewel/clearskies/blob/master/protocol/core.md#tree-merge-algorithm).  (This doesn't explicitly mention deleted files but they do not need special treatment for that merge.)

There was an issue in the software that were causing it to exhibit the behavior you found.  The scanner wasn't setting the "deleted" flag back to false if the file appeared again.

There was also a race condition of sorts that would have caused problems when "B" is offline when "A" deletes the file.  The connection code wasn't marking a file as deleted before deleting it, which caused the scanner to re-detect the deletion on the "B" side as if it had been deleted again, which would update the utime.

Thanks again for the report, let me know if the latest version fixes the problem for you.

**Comment by cachapa** [comment]
Thanks for the quick response.

I tried to test the fix, but after pulling from git I couldn't get the software to work properly.
Do I need to re-create the share every time I start the daemon? Simply starting the daemon didn't work, so I guess saving the state isn't yet implemented?

In any case, I tried recreating the share but am having errors:

```
cachapa@server:~/clearskies$ ./clearskies create ../share
/home/cachapa/clearskies/lib/control_client.rb:14:in `[]=': can't convert Symbol into Integer (TypeError)
    from /home/cachapa/clearskies/lib/control_client.rb:14:in `issue'
    from ./clearskies:178:in `<main>'
```

I even tried to clone the git repo from scratch, but that didn't help.

**Comment by jewel** [comment]
Saving state is implemented.  It looks like the "create" command never has worked.  The "share" command has an implicit create so that's probably why it worked before.  I have pushed cd1acdd9f917cbffa0eba19ffdd19e9f04423531 which should fix the create command.

**Comment by cachapa** [comment]
Sorry, that was my bad, I got confused with the commands.

I also found the configuration folder under ~/.local/share/clearskies and deleted everything inside, to make sure.
The share command works, but I'm still getting weird behaviour:
1. Copy file to A, it appears in B
2. Delete it from A, it is deleted from B
3. Copy it again into A, there's nothing in B

It seems if I edit the file before or after adding it to A, it does appear in B.

One easy way to test this is:
1. Add file named "test" to A
2. Rename the file to "testt"
3. Rename it back to "test". This makes it disappear from B

**Comment by jewel** [comment]
I can confirm that it doesn't work.  When I added a test earlier to test for the case you mentioned I deleted a file and then created a new, different file with the same name.

It looks like if the file is recreated with the same name and same contents, then it doesn't work.  I imagine this is because the SHA hash matches and so the connection code thinks that the file already is present and doesn't need to be downloaded again.  I've added a test for this case in d1b3bae7125c648993087ad2ef1bcf7830f4677c, and will fix it tomorrow.

**Comment by jewel** [comment]
OK, my test is passing now.  Do you want to check and if it's fixed for you, close this issue?

**Comment by cachapa** [comment]
Seems to be working fine now.

I noticed another problem though, which is possibly related:
1. ./clearskies stop on B
2. Delete file on A
3. ./clearskies start on B
4. File exists on B but not on A

Renaming or editing the the file on B creates it on A.

Do you want to close this issue and open another one?

**Comment by jewel** [comment]
We can keep the same issue for these deleted file sync issues.  I can reproduce the problem and have added an automated test that does so.  I should have a fix soon.

Thanks for finding so many issues with deleted files, my tests obviously were insufficient.

**Comment by jewel** [comment]
OK, it turns out that deleted files were being excluded from the first manifest shared on initial connection.  It should be fixed now.  Can you confirm?

**Comment by cachapa** [comment]
It's working perfectly as far as my testing went.
I'm closing this. Thanks!
